version: '3.8'

services:
  frontend:
    build:
      context: ./fraud-dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fraud-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./api/best_model_LightGBM_20250310_193850.joblib:/app/best_model_LightGBM_20250310_193850.joblib
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge 