services:
  - type: web
    name: fraud-detection-frontend
    env: docker
    dockerfilePath: ./fraud-dashboard/Dockerfile
    buildCommand: docker build -t fraud-detection-frontend ./fraud-dashboard
    startCommand: docker run -p 80:80 fraud-detection-frontend
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: fraud-detection-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    buildCommand: docker build -t fraud-detection-api ./api
    startCommand: docker run -p 5000:5000 fraud-detection-api
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
    autoDeploy: true 