services:
  # Backend API Service
  - type: web
    name: fraud-detection-api
    env: python
    buildCommand: cd api && pip install -r requirements.txt
    startCommand: cd api && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production

  # Frontend Static Site
  - type: static
    name: fraud-detection-frontend
    env: node
    buildCommand: cd fraud-dashboard && npm install && npm run build
    staticPublishPath: ./fraud-dashboard/dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production 