[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fraud-detection-api"
version = "1.0.0"
authors = [
    { name = "Your Name" }
]
description = "Fraud Detection API"
requires-python = ">=3.9" 